[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_staking = "AvkGefXsDuKULstEBSFW8i32nF4r8MWBUpWZqAzLhgXL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/kien6034/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
